# CONSTRUCCIÓN
FROM node:24.13.0-bookworm-slim AS builder

WORKDIR /app
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable && corepack prepare yarn@4.12.0 --activate

COPY frontend/package.json frontend/yarn.lock ./
RUN yarn config set nodeLinker node-modules
RUN yarn install --frozen-lockfile

COPY frontend ./

# Crea la carpeta /app/dist con los archivos estáticos optimizados
RUN yarn build

# PRODUCCIÓN (Servidor Web Estático)
FROM nginx:alpine

# Copia los archivos compilados de React a la carpeta pública de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Configura este Nginx interno para que React Router funcione bien
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]