# Definición de zonas para Rate Limiting
# Zona para delimitar el Login: 5 peticiones por minuto por IP
limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;

# Zona para limitar el registro: 3 peticiones por minuto por IP
limit_req_zone $binary_remote_addr zone=register_limit:10m rate=3r/m;

upstream frontend {
    server frontend:5173;
}

upstream backend {
    server backend:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    #Bloquear acceso a archivos ocultos (.env, .git, .htaccess, etc)
    location ~ /\.(.*)$ {
        deny all;
    }

    #Bloquear archivos de configuración o backups
    location ~* \.(env|ini|log|sql|bak|old|backup)$ {
        deny all;
    }

    #Bloquear acceso al directorio .git completo
    location ^~ /.git {
        deny all;
    }

    #Bloquear archivos de Docker, CI/CD o configuraciones internas
    location ~* /(docker-compose\.yml|Dockerfile|Makefile|composer\.json|package\.json)$ {
        deny all;
    }

    # Proteger Login
    location = /api/auth/login {
        limit_req zone=login_limit burst=2 nodelay;
        
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend;
        
        # Propaga la IP real para que el backend la conozca si lo necesita
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proteger Registro
    location = /api/users/register {
        limit_req zone=register_limit burst=1 nodelay;
        
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend;
    }
}